[package]
name = "drt"
version = "0.1.0"
authors = ["Sean McEligot <sean.mceligot@gmail.com>"]

[lib]
name = "drt"
path = "src/lib.rs"

[[bin]]
name = "drt"
path = "src/main.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.8"

[dev-dependencies]
quickcheck = "0.6"
#quickcheck_macros = "0.6"
