[package]
name = "confsync"
version = "0.0.1"
authors = ["Sean McEligot <sean.mceligot@gmail.com>"]

regex = "0.1.26"
getopts = "0.2.9"


[dependencies]
regex = "*"
getopts = "*"
glob = "*"
tempfile = "*"
