[package]
name = "drt"
version = "0.0.1"
authors = ["Sean McEligot <sean.mceligot@gmail.com>"]

regex = "*"
getopts = "*"

[dependencies]
regex = "*"
getopts = "*"
glob = "*"
tempfile = "*"
rand = "*"
